TEST 2
Signed-off-by: kuvaldini <ivan@kuvaldini.pro>

diff --git a/.github/build-iroha1.src.yml b/.github/build-iroha1.src.yml
--- a/.github/build-iroha1.src.yml
+++ b/.github/build-iroha1.src.yml
@@ -749,10 +749,12 @@ jobs:
       -
         name: REMOVE ME NOW - generate core dump
         run: |
-          sleep 3 & kill -11 $! ; ls -lA; exit 1
+          sleep 3 & kill -11 $! ; ls -lA;
+          echo 'int main(){int a=*(int*)nullptr; }' | gcc -xc++ - -o segfault ; ./segfault
+          # exit 1
       -
         name: (optional) Upload artifact coredumps
-        if: failure()
+        # if: failure()
         uses: actions/upload-artifact@v2
         with:
           name: coredumps-${{env.ARTIFACT_SUFFIX}}
