[CI][GHActions] Introduce GitHub Actions Iroha1 (#1028)
* [GHActions] Introduce GitHub Actions Iroha1

build_iroha_deps.sh update and made reentrant
Check if GitHub workflows correspond to sources
Disable slow s390 in Jenkins
remove TBB from dependancies
Chatops

Signed-off-by: kuvaldini <ivan@kuvaldini.pro>

diff --git a/docker/develop/Dockerfile b/docker/develop/Dockerfile
--- a/docker/develop/Dockerfile
+++ b/docker/develop/Dockerfile
@@ -46,16 +46,21 @@ RUN mkdir ${GOPATH}
 ENV PATH=${PATH}:/opt/go/bin:${GOPATH}/bin
 RUN go get github.com/golang/protobuf/protoc-gen-go
 
+## pip3 contains fresher versions of packages than apt
+RUN pip3 install --no-cache-dir cmake ninja
+
 # install dependencies
 COPY vcpkg /tmp/vcpkg-vars
-RUN set -e; \
-    export VCPKG_FORCE_SYSTEM_BINARIES=1; \
-    sh /tmp/vcpkg-vars/build_iroha_deps.sh /tmp/vcpkg /tmp/vcpkg-vars; \
+RUN set -xe; \
+    case "$(uname -m)" in  arm*|s390*|ppc64*)  export VCPKG_FORCE_SYSTEM_BINARIES=1 ;; esac; \
+    /tmp/vcpkg-vars/build_iroha_deps.sh /tmp/vcpkg /tmp/vcpkg-vars; \
     /tmp/vcpkg/vcpkg export $(/tmp/vcpkg/vcpkg list | cut -d':' -f1 | tr '\n' ' ') --raw --output=dependencies; \
     mv /tmp/vcpkg/dependencies /opt/dependencies; \
     chmod +x /opt/dependencies/installed/*/tools/protobuf/protoc*; \
     unset VCPKG_FORCE_SYSTEM_BINARIES; \
     rm -rf /tmp/vcpkg*
+    ##NOTE Newer packages like libpq may require newer cmake version, and will fail with no sanity error message when VCPKG_FORCE_SYSTEM_BINARIES=1;
+    ##NOTE But vcpkg on platforms arm,s390,ppc64 require VCPKG_FORCE_SYSTEM_BINARIES=1
 
 # install sonar cli
 ENV SONAR_CLI_VERSION=3.3.0.1492
