[GHActions] ctest
Signed-off-by: Ivan 'kuvaldini' Kuvaldin <ivan@kuvaldini.pro>

diff --git a/.github/workflows/build-iroha1.yml b/.github/workflows/build-iroha1.yml
--- a/.github/workflows/build-iroha1.yml
+++ b/.github/workflows/build-iroha1.yml
@@ -58,9 +58,9 @@ jobs:
         # USE_URSA: [ -DUSE_URSA=OFF ]
         ## FIXME USE_BURROW=ON Fails on macos https://github.com/kuvaldini/iroha/runs/2489119287?check_suite_focus=true
         build_type: [Debug] #,Release, RelWithDebInfo
-    env:
-      CC: ${{ matrix.cc }}
-      CXX:
+    # env:
+    #   CC:  ${{ matrix.cc }}
+    #   CXX: 
     steps:
       - name: export CC and CXX
         run: |
@@ -103,11 +103,7 @@ jobs:
         ## Takes 18m44s on regular GitHub runner
       - if: ${{ false }} # disable for now
         name: CTest
-        run: |
-          set -eu
-          initdb --locale=C -E UTF-8 $PWD/postgres_database
-          pg_ctl -D $PWD/postgres_database start & { sleep .3; kill -0 $!; }
-          cd build && ctest --output-on-failure --progress
+        run: "set -eu\npg_ctlcluster 12 main start \n###initdb --locale=C -E UTF-8 $PWD/postgres_database\n###pg_ctl -D $PWD/postgres_database start & { sleep .3; kill -0 $!; }\ncd build && ctest --output-on-failure #--progress\n"
         ## Takes over 4h on regular GitHub runner
   build-iroha-macos:
     if: ${{ false }} # disable for now
@@ -170,12 +166,8 @@ jobs:
         ## ToDo may be optimize, i.e. cache package
       - if: ${{ false }} # disable for now
         name: CTest
-        run: |
-          set -eu
-          initdb --locale=C -E UTF-8 $PWD/postgres_database
-          pg_ctl -D $PWD/postgres_database start & { sleep .3; kill -0 $!; }
-          cd build && ctest --output-on-failure --progress
-        # DEBIAN_FRONTEND=noninteractive apt-get install postgersql
+        run: "set -eu\npg_ctlcluster 12 main start \n###initdb --locale=C -E UTF-8 $PWD/postgres_database\n###pg_ctl -D $PWD/postgres_database start & { sleep .3; kill -0 $!; }\ncd build && ctest --output-on-failure #--progress\n"
+        ## Takes over 4h on regular GitHub runner
   build-iroha-windows:
     if: ${{ false }} # disable for now
     runs-on: windows-latest
