TEST 2
Signed-off-by: kuvaldini <ivan@kuvaldini.pro>

diff --git a/.github/workflows/build-iroha1.yml b/.github/workflows/build-iroha1.yml
--- a/.github/workflows/build-iroha1.yml
+++ b/.github/workflows/build-iroha1.yml
@@ -781,9 +781,9 @@ jobs:
         if: ${{false}}
       - name: REMOVE ME NOW - generate core dump
         run: |
-          sleep 3 & kill -11 $! ; exit 1
+          sleep 3 & kill -11 $! ; ls -lA; exit 1
       - name: (optional) Upload artifact coredumps
-        if: failure()
+        #if: failure()
         uses: actions/upload-artifact@v2
         with:
           name: coredumps-${{env.ARTIFACT_SUFFIX}}
@@ -1108,9 +1108,9 @@ jobs:
         if: ${{false}}
       - name: REMOVE ME NOW - generate core dump
         run: |
-          sleep 3 & kill -11 $! ; exit 1
+          sleep 3 & kill -11 $! ; ls -lA; exit 1
       - name: (optional) Upload artifact coredumps
-        if: failure()
+        #if: failure()
         uses: actions/upload-artifact@v2
         with:
           name: coredumps-${{env.ARTIFACT_SUFFIX}}
