feat: get logs from failing ci
Signed-off-by: Lohachov Mykhailo <lohachov@soramitsu.co.jp>

diff --git a/.github/workflows/iroha2-dev-pr.yml b/.github/workflows/iroha2-dev-pr.yml
--- a/.github/workflows/iroha2-dev-pr.yml
+++ b/.github/workflows/iroha2-dev-pr.yml
@@ -219,7 +219,11 @@ jobs:
           cache-to: type=gha,mode=max
       - name: Test docker-compose.single.yml
         run: |
-          docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.single.yml up --wait || exit 1
+          docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.single.yml up --wait || {
+            echo "docker-compose failed. Logs:";
+            docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.single.yml logs --tail="all";
+            exit 1;
+          }
           docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.single.yml down
       - name: Test docker-compose.local.yml
         run: |
