chore:cleanup
Signed-off-by: Lohachov Mykhailo <lohachov@soramitsu.co.jp>

diff --git a/.github/workflows/iroha2-dev-pr.yml b/.github/workflows/iroha2-dev-pr.yml
--- a/.github/workflows/iroha2-dev-pr.yml
+++ b/.github/workflows/iroha2-dev-pr.yml
@@ -227,7 +227,11 @@ jobs:
           docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.single.yml down
       - name: Test docker-compose.local.yml
         run: |
-          docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.local.yml up --wait || exit 1
+          docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.local.yml up --wait || {
+            echo "docker-compose failed. Logs:";
+            docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.local.yml logs --tail="all";
+            exit 1;
+          }
           docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.local.yml down
       - name: Run docker-compose.yml containers
         run: docker compose -f ${{ env.DEFAULTS_DIR }}/docker-compose.yml up --wait || exit 1
